### ISSUE TITLE
Please add my signature to the letter of support 

### ISSUE THREAD

**Issue by Manu343726** [patricia-gallardo/patricia-gallardo.github.io#117]
Hi Patricia, 

Please add my signature (Manu Sánchez) to the support letter of the proposed includecpp transparency report on cppcon and the requests for the isocpp foundation and cppcon org outlined in the other documents.

Let me use this issue to thank you again for stepping forward on this. You and all the people involved have done a great service to the community with your courage. Than you all.

**Comment by patricia-gallardo** [comment]
Thank you! I forgot to mention the issue in the commit message but it is done <3
